application:
  name: "tide-example"
  project: "tide-example"
  organization: "QoveryCommunity"
routers:
- name: "main-tide-example"
  routes:
  - application_name: "tide-example"
    paths:
    - "/"