application:
  name: tide-example
  project: tide-example
  publicly_accessible: true
  organization: QoveryCommunity
routers:
- name: main
  custom_domains:
    - branch: main
      domain: tide-example.jmnorlund.net
  routes:
  - application_name: tide-example
    paths:
    - /
