application:
  name: tide-example
  project: tide-example
  publicly_accessible: true
  organization: QoveryCommunity
routers:
- name: main
  routes:
  - application_name: tide-example
    paths:
    - /
